# Generated by Django 4.2.4 on 2024-02-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.IntegerField()),
                ('img', models.ImageField(max_length=255, null=True, upload_to='uploaded_img/')),
            ],
        ),
    ]
